# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a6929828b08583eed5da2fe10fb0b55915448a5c9a8f6f09793c3a393b570f29cfe2479dc35390c69ba91197b98662aaca4c5b51d6cc08c0886477996d2dd32

test:
  secret_key_base: b624a1719319de7a40b05a6c3f360ceb408768683464c1bdd8d62e80462fce9af3ead4a70538f423c67cff330a61230ca097b4f19e0f2c8c2bd991074f748fc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
